services:
  postgres:
    image: postgres:17-alpine
    container_name: codeatlas-postgres

    environment:
      POSTGRES_USER: codeatlas
      POSTGRES_PASSWORD: codeatlas_dev
      POSTGRES_DB: codeatlas

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeatlas -d codeatlas"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.3
    container_name: codeatlas-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20

    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: codeatlas-redis

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


volumes:
  postgres_data:
  elasticsearch_data:
  redis_data: